### ISSUE TITLE
Website doesn't load

### ISSUE THREAD

**Issue by p-fernandez** [stursby/hasvuepassedreactyet#4]
In Chrome Canary and Brave, website is not being loaded properly.

OS: OSX 10.13.5
Browsers: 

- Chrome Canary Version 69.0.3457.2 (Official Build) canary (64-bit)
- Brave 0.22.810

<img width="736" alt="screen shot 2018-06-15 at 12 06 25" src="https://user-images.githubusercontent.com/18152036/41462914-cabd9f70-7094-11e8-90f1-0e0f8d52a97f.png">

**Comment by Zomis** [comment]
Do you really see the "JavaScript enabled" message on the screen?

I bet that the problem is because of the request to fetch the github stars, which is currently rate-limited, probably because this site has so many visits today.
![screenshot from 2018-06-15 12 17 27](https://user-images.githubusercontent.com/1405379/41463265-253bb846-7096-11e8-9193-132c616e5b4b.png)
